import type { Metadata } from 'next';
import type { Viewport } from 'next';
import { Inter } from 'next/font/google';

import './styles/globals.css';
import { Footer } from '@/widgets/footer';
import { Header } from '@/widgets/header';
import { ModalProvider } from './provider/modal-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SHOPPE',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ModalProvider />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
